Add docs for DataRegistrations
SpongePowered/SpongeDocs pull request #609
Opened 2017-06-18 07:07 UTC by ZephireNZ

This adds documentation for the new registration pattern in Sponge 6.0.0. I also mention that there is a list of `TypeTokens` now in the API :)

I also fixed a few typos from my previous data docs PR

2017-06-18 07:09 UTC, Spongy commented
Setting up PR reference, please wait...

2017-06-18 07:40 UTC, gabizou requested changes
Minor changes. looks good otherwise.

2017-06-18 07:40 UTC, gabizou commented on source/plugin/data/custom/datamanipulators.rst
> +          .setManipulatorId("my_custom")
You need the name for the manipulator registration.

2017-06-18 07:40 UTC, gabizou commented on source/plugin/data/custom/datamanipulators.rst
> +      DataRegistration.<MyCustomData, ImmutableCustomData>builder()
The generics are not absolutely required since it returns a wildcard.

2017-06-18 07:40 UTC, gabizou commented on source/plugin/data/custom/datamanipulators.rst
> +    The ID is the class' canonical name, such as ``com.example.MyCustomData``.
This is also utilized in the event that legacy data is being "upgraded" from an older manipulator id.

2017-06-19 09:11 UTC, ZephireNZ commented on source/plugin/data/custom/datamanipulators.rst
> +      DataRegistration.<MyCustomData, ImmutableCustomData>builder()
In my defence I shamelessly copied from your PR xD

2017-06-19 09:28 UTC, ZephireNZ commented
@gabizou how does she look now?

2017-06-19 15:11 UTC, gabizou reviewed
Server isn't the only way data registration works ;)

2017-06-19 15:11 UTC, gabizou commented on source/plugin/data/custom/datamanipulators.rst
> +:javadoc:`DataRegistration` and automatically register it with the server.
s/server/game/

2017-06-19 15:11 UTC, gabizou commented on source/plugin/data/custom/datamanipulators.rst
> +server/plugin can create copies of your data and serialize/deserialize your data without referencing any of your classes
s/server/game/

2017-06-19 21:17 UTC, ZephireNZ commented
Done. In reality the server is still there on a client-side single player ;P

2017-06-20 13:51 UTC, gabizou commented
> Done. In reality the server is still there on a client-side single player ;P

Yes, but in all context, data is registered for the game instance, not just the server instance (You can have multiple server instances in one game lifecycle)

2017-06-20 13:51 UTC, gabizou approved these changes

2017-06-21 06:55 UTC, Inscrutable requested changes
Typo and weird grammar. Fix them and we're all done.

2017-06-21 06:55 UTC, Inscrutable commented on source/plugin/data/custom/datamanipulators.rst
> +    values. Sponge provides a long list of pre-buit tokens for the API in :javadoc:`TypeTokens`.
Typo. pre-built

2017-06-21 06:55 UTC, Inscrutable commented on source/plugin/data/custom/datamanipulators.rst
> +    listening to :javadoc:`GameInitializationEvent` such as the below. If you try to register a ``DataManipulator`` once
"such as the below" needs fixing ... please either add the word "example" or remove the "the".

2017-06-22 08:40 UTC, Inscrutable approved these changes

2017-06-22 08:44 UTC, merged