Updated BungeeCord docs
SpongePowered/SpongeDocs pull request #682
Opened 2018-04-15 14:45 UTC by phit

As it has been years at this point and the PR's have no progress,
I'd rather link to an actual solution to people, tired of having to link
people a solution when it could just be in the Docs.

Also moved without IP Forwarding to the end as nobody should be really using that, and with is more important.

2018-04-15 21:18 UTC, ST-DDT requested changes

2018-04-15 21:18 UTC, ST-DDT commented on source/server/getting-started/bungeecord.rst
> +* In Sponge's config (``config/sponge/global.conf``), set ``modules.bungeecord`` to ``true`` and ``bungeecord.ip-forwarding`` to
Please limit the line length to 120 characters. (split before ``bungeecord.ip-forwarding``)

2018-04-15 21:18 UTC, ST-DDT commented on source/server/getting-started/bungeecord.rst
> +
Duplicate empty line

2018-04-15 21:18 UTC, ST-DDT commented on source/server/getting-started/bungeecord.rst
> +`Pull <https://github.com/SpigotMC/BungeeCord/pull/1557>`_ `requests <https://github.com/SpigotMC/BungeeCord/pull/1678>`_
I would go for `Pull requests: #1557 and #1678` so you actually see that there are more than one PRs releated to that, (but thats optional IMO)
Also watch the line length ( 121 > 120 ;-) ).

2018-04-15 21:27 UTC, phit commented on source/server/getting-started/bungeecord.rst
> +`Pull <https://github.com/SpigotMC/BungeeCord/pull/1557>`_ `requests <https://github.com/SpigotMC/BungeeCord/pull/1678>`_
the numbers mean nothing to readers, and you can see it's two links as the blue line of a link does not include the space between

2018-04-15 21:27 UTC, phit commented on source/server/getting-started/bungeecord.rst
> +* In Sponge's config (``config/sponge/global.conf``), set ``modules.bungeecord`` to ``true`` and ``bungeecord.ip-forwarding`` to
it was already above 120 qq

2018-04-15 21:35 UTC, ST-DDT approved these changes
I cannot test the technical details of this, but otherwise it looks good to me.

2018-04-15 21:38 UTC, ST-DDT commented
Why does Travis CI not try to build this PR? It works (at least locally for me).

2018-04-16 10:24 UTC, connorhartley commented
@ST-DDT It's apparently listed as Abuse on Travis, @phit is going to try contact their support to clear that up.

2018-04-17 07:29 UTC, kashike commented
@phit was caught stealing cookies from their cookie jar.

2018-04-17 08:58 UTC, dualspiral commented
I don't think SpongePls is maintained any more and does not support negative packet IDs that some mods like to use. I think we should just be suggesting Waterfall for simplicity (other forks are available).

Otherwise, I have no interest in chasing up the Bungee PRs any further so I agree with the removal of those statements.

2018-04-17 15:02 UTC, phit commented
Waterfall has issues with mods too, which come from upstream..
https://github.com/WaterfallMC/Waterfall/issues/136 
https://github.com/HexagonMC/BungeeCord/issues/148
https://github.com/WaterfallMC/Waterfall/issues/216

both of which I had to "fix" for my server [1](https://github.com/Stonebound/BungeeCord/commit/00b5d0bf6c62cc7656a0cf39844a52279e6bd5d9)  [2](https://github.com/Stonebound/BungeeCord/commit/2d1ad7d77cc70b2073b7bd92b608edfd5066c8d6)
so really it doesn't matter, both options have issues

2018-04-19 11:04 UTC, Inscrutable commented on source/server/getting-started/bungeecord.rst
> +While it is recommended that you use IP Forwarding wherever possible. If you do not wish to do so, simply ensure that
Broken clause. Delete the While.

2018-04-19 11:17 UTC, phit commented on source/server/getting-started/bungeecord.rst
> +While it is recommended that you use IP Forwarding wherever possible. If you do not wish to do so, simply ensure that
I didn't even write this, but done..

2018-04-20 01:35 UTC, merged