added visual studio code text.rst
SpongePowered/SpongeDocs pull request #701
Opened 2018-06-14 15:33 UTC by josephworks

2018-06-14 19:59 UTC, ST-DDT commented
Has VSC direct support for reST or do you need a plugin for that?

2018-06-14 20:00 UTC, ST-DDT approved these changes

2018-06-14 20:02 UTC, phit commented
needs a plugin

2018-06-15 01:40 UTC, josephworks commented
done

2018-06-15 05:26 UTC, ST-DDT approved these changes

2018-06-15 15:41 UTC, Inscrutable requested changes
Thanks for the additions. Can you please fix the quibbles I have highlighted?

2018-06-15 15:41 UTC, Inscrutable commented on source/preparing/text.rst
> +reST Extention can be downloaded for free from https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext
Spelling error. Extention -> Extension

2018-06-15 15:41 UTC, Inscrutable commented on source/preparing/text.rst
> +Visual Studio Code is a source code editor developed by Microsoft for Windows, Linux and macOS. It includes support for debugging,
Please keep line lengths 120 characters or below, to avoid wrapping. (It's one of our guidelines).

2018-06-16 01:27 UTC, Inscrutable approved these changes

2018-06-16 01:32 UTC, merged