I did it
SpongePowered/SpongeDocs pull request #706
Opened 2018-06-26 01:52 UTC by parlough

2018-06-26 01:59 UTC, Spongy commented
Setting up PR reference, please wait...

2018-06-26 02:11 UTC, kashike requested changes

2018-06-26 02:11 UTC, kashike commented on source/about/staff.rst
> +| parlough                          | Developer                          |
Should be moved to the correct alphabetical position.

2018-06-26 02:13 UTC, kashike approved these changes

2018-06-26 08:48 UTC, ST-DDT approved these changes

2018-06-26 08:49 UTC, merged

2018-06-28 03:11 UTC, Inscrutable reviewed
Yeah.