Elaborate on Ore Naming Guidelines
SpongePowered/SpongeDocs pull request #709
Opened 2018-07-01 19:55 UTC by phase

I added some more examples of plugin names that are right & wrong on Ore.

2018-07-01 21:24 UTC, simon816 commented
Not sure on the Ore* restrictions, it could be a bit over-reaching.

2018-07-01 22:36 UTC, ST-DDT requested changes
Not sure on the `Ore`-Stuff either. But if thats the rule, that's OK for me.

2018-07-01 22:36 UTC, ST-DDT commented on source/ore/guidelines.rst
> +- *SpongeWarp*
You have to add an empty line before the first entry to make this bulleted list work.

````text
text:

* entry 1
* entry 2
````

2018-07-01 22:36 UTC, ST-DDT commented on source/ore/guidelines.rst
> +- *CoolWarps-Sponge*
Same here

2018-07-01 23:22 UTC, phase commented
Removed `Ore*` restrictions (those can go case by case) and fixed the lists.

2018-07-01 23:27 UTC, dualspiral submitted a review, later dismissed

2018-07-01 23:27 UTC, dualspiral commented on source/ore/guidelines.rst
> +Examples of names that are **wrong**:
wrong -> not acceptable

2018-07-01 23:27 UTC, dualspiral commented on source/ore/guidelines.rst
> +Examples of names that are **right**:
right -> acceptable

2018-07-01 23:41 UTC, phase commented
Changed language

2018-07-02 16:57 UTC, ST-DDT approved these changes

2018-07-03 17:16 UTC, Spongy commented
Setting up PR reference, please wait...

2018-07-11 09:10 UTC, merged