Info about getting a log message to appear in a newly created plugin
SpongePowered/SpongeDocs pull request #724
Opened 2018-07-25 20:32 UTC by uglycoyote

see #644 

when getting started on a new plugin for the first time, one needs a way to verify that it works, and printing one line to a log seems like a good start.   I wanted to update the docs to make this a bit more straightforward since I stumbled on this more than I should have when trying to get things rolling.

2018-07-25 22:35 UTC, phit commented
maybe add `logger.info` (this will show in console) too?

2018-07-25 23:41 UTC, uglycoyote commented
@phit  that is good.  I didn't realize info's would come to the console and debug's would not.  I can remove the big "Tip" that I added to the page then.

2018-07-26 01:25 UTC, ryantheleach commented
Nice update! It's good as-is, but a potential improvement could be made that you wouldn't be aware about. (and the previous example wasn't any better in this regard)

Code examples don't get translated through our translation system, in order to prevent symbol names changing.

So a soft rule of thumb the docs team has, is that if a comment in the code is meaningful, it should also be restated outside of the code block so that it's translate-able.

2018-07-26 04:45 UTC, uglycoyote commented
@ryantheleach thanks, based on this  I decided to remove the long comments and add a bit of extra text above the code sample.  I guess the translation is automated?  I noticed when browsing the documentation auf Deutsch that the "Note" and "Tip" highlighted sections also remain in English, which seems strange.   I wonder if the translation mechanism has some settings that can be tweaked to get those to translate as well?

2018-07-26 05:51 UTC, ST-DDT commented
The translation is done by our translators and is not automated. German currently has a translation coverage of about 60%. So there might be entire pages that still have to be translated but the community is on it. AFAICT the information boxes are translateable as well (see the index page) but that particular might not have been translated yet.

2018-07-26 06:24 UTC, ryantheleach commented
The specific part you are talking about, Note vs Tip, is probably due to those being a part of the theme.

2018-07-26 07:30 UTC, uglycoyote commented
It was the contents of the Notes and Tips that was not translated.  But looking at other languages I saw that the Notes and Tips of those were translated.  As @ST-DDT says, it's a manual process so I guess the translators have not gotten to those parts for whatever reason.  I'm impressed that there's manual translation!

2018-07-26 09:57 UTC, Inscrutable approved these changes

2018-07-26 12:53 UTC, 12awsomeman34 requested changes
Minor stuff really...

2018-07-26 12:53 UTC, NariKiro commented on source/plugin/plugin-class.rst
> +The example below will log a message upon starting the server.  If your plugin is correctly loaded, you should see this message as part of the server's initialization output.
An extra space before If

2018-07-26 12:53 UTC, NariKiro commented on source/plugin/plugin-class.rst
> +        {
Minor, but most examples follow the Sponge guidelines and leave the `{` on the same line as the function

2018-07-26 12:55 UTC, NariKiro commented on source/plugin/plugin-class.rst
> +The example below will log a message upon starting the server.  If your plugin is correctly loaded, you should see this message as part of the server's initialization output.
Looking at this again, it's a really long line that should be divided into two, ref: https://github.com/SpongePowered/SpongeDocs/pull/725#discussion_r205389138

2018-07-26 16:30 UTC, uglycoyote commented
I wrapped the long lines and moved the curly brace to conform with the coding standard.

2018-07-26 17:34 UTC, Spongy commented
Setting up PR reference, please wait...

2018-07-26 17:36 UTC, ST-DDT approved these changes

2018-08-04 14:31 UTC, ST-DDT commented
@NariKiro Can you review this again? Are all issues fixed so we can merge this?

2018-08-04 14:39 UTC, NariKiro commented on source/plugin/plugin-class.rst
> +The example below will log a message upon starting the server.  If your plugin is correctly loaded,
Still two spaces before If in this sentence, but that has no effect on the preview itself. Everything else is fine.

2018-08-05 04:14 UTC, 12awsomeman34 approved these changes

2018-08-05 08:48 UTC, ST-DDT approved these changes

2018-08-06 10:45 UTC, merged

2018-08-07 02:06 UTC, uglycoyote commented
@inscrutable thanks for fixing the space problem.  Sorry was out of touch for a bit on this one, been doing some handyman projects that took up all my free time.