Document catalog types. Fixes #185.
SpongePowered/SpongeDocs pull request #736
Opened 2018-08-06 19:31 UTC by ST-DDT

Fixes #185.

2018-08-06 19:32 UTC, Spongy commented
Setting up PR reference, please wait...

2018-08-06 19:32 UTC, ST-DDT reviewed
I'm not sure where this topic fits bets. I put it under data as a first try.

2018-08-06 19:32 UTC, ST-DDT commented on source/plugin/data/index.rst
> +CatalogTypes
Not sure on the positioning of this topic.

2018-08-08 12:14 UTC, Inscrutable requested changes
Excellent, more Spongification! 
I have quibbled with the grammar and punctuation here and there. Whether it works as described is someone else's problem.

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +A big part of the data API consists of special values with a specific meaning. In previous versions of minecraft this
"these" (it's plural)

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +have been numbers such as ``1`` that meant something specific in a given context for example a simple stone in
comma needed after "context"

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +the ``/give`` command. From version to version minecraft moved away from these magics numbers and moved to a more
"More recent versions of Minecraft moved away from these magic numbers, and ..."
We should be capitalising Minecraft in general, I believe. (there's a lowercase one in the 2nd sentence too)

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +Because of this Sponge introduced a new class of data: :javadoc:`CatalogType`\s.
comma needed after "this"

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +``CatalogType``\s provide two methods make them very versatile.
"... two methods that make them ..."

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +First the :javadoc:`CatalogType#getId()` method that provides an easy access to a unique identifier (within that type of
"First, the :javadoc:`CatalogType#getId()` method provides an ..."

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +Sponge's :doc:`config serialization <../configuration/serialization>` to do this for you instead. Some ids are not
If this is the second method, it probably justifies a second paragraph starting at "Some ids are ..."

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +:javadoc:`GameRegistry#getAllOf(Class)` method, it also offers various other ways of retrieving a ``CatalogType`` and
Turn the comma after "method" into a semicolon (or a full stop and start a new sentence, take your pick).

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +Sometimes we just want to reference a ``CatalogType`` entry in our code without actually getting it from the registry,
Turn the comma after "registry" into a semicolon.

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +this is usually the case for default values. To simplify these usecases there are so called catalog classes which
"use-cases"
why are they "so called"?

2018-08-08 12:14 UTC, Inscrutable commented on source/plugin/data/catalog-types.rst
> +class please also check the parent and child classes. If the class has to many variants or variants can be added and
to -> too

2018-08-08 21:22 UTC, gabizou approved these changes
Documentation is good.

2018-08-09 06:43 UTC, ST-DDT commented
@worm424 i could you please explain why you closed this? If you have done so in a different place, then I haven't found it.

2018-08-09 09:38 UTC, Inscrutable commented
I have no idea what happened here.

2018-08-09 09:50 UTC, Inscrutable approved these changes

2018-08-09 10:04 UTC, worm424 commented
Sorry  @ST-DDT  it won't happen again

2018-08-10 09:52 UTC, merged