Add a note about thread safety. Fixes #242.
SpongePowered/SpongeDocs pull request #738
Opened 2018-08-07 17:09 UTC by ST-DDT

Fixes #242.

2018-08-07 17:11 UTC, Spongy commented
Setting up PR reference, please wait...

2018-08-08 00:25 UTC, ryantheleach commented
Needs to be stronger IMO. Most of the game thread in Minecraft is **not** thread safe, so there needs to be details regarding caching that data, and polling for it when it could change.

It may not be efficient, but it is correct, and SOMEONE will absolutely call permissions from off-thread and expect it to work.

2018-08-08 00:27 UTC, ryantheleach requested changes
Needs to be stronger IMO. Most of the game thread in Minecraft is not thread safe, so there needs to be details regarding caching that data, and polling for it when it could change.

It may not be efficient, but it is correct, and SOMEONE will absolutely call permissions from off-thread and expect it to work, based on staff comments (if it's not explicitly written anywhere that permissions is threadsafe).

Happy to accept as-is though, but would like more.

2018-08-08 00:29 UTC, ryantheleach commented
A simple non-threadsafe context that could be used for example is "near spawn" for anti-spawn camping permissions.

The position of the player would need to be cached every tick, or maybe a move listener that determines where the player is. should be stored in a concurrent map of some sort, or lock on entries or something.

2018-08-09 18:01 UTC, ST-DDT commented
@ryantheleach Like this? Or should I add an explicit example of something bad?

2018-08-10 01:12 UTC, ryantheleach commented
LGTM;

"add an explicit example of something bad"

Merge it as-is, if you feel like it, add an example of something **good** only.  I feel like Users will already know how to do something bad, and that offering them a bad code example will only make them "I can't be bothered making it correctly" and copy the bad example because it looks simpler then the good example.

The note captures what needs to be said perfectly.

2018-08-10 08:02 UTC, Inscrutable requested changes
I quibbled a couple of weird sentences. Good show.

2018-08-10 08:02 UTC, Inscrutable commented on source/plugin/permissions.rst
> +    ``ContextCalculator`` implementations must be **thread safe**, because someone will be calling it from outside of
It's a Plural. We also try to use passive third person, ie.
"because they may be called from outside of the main thread, or even called in parallel."

2018-08-10 08:02 UTC, Inscrutable commented on source/plugin/permissions.rst
> +    ``ContextCalculator``\s (such as location based ones) have to utilize some kind of cache and must be to be updated
"... ones) have to utilize a cache, and must be updated ..."
(Do we really need "some kind of"?)

2018-08-11 02:58 UTC, Inscrutable approved these changes

2018-08-11 12:04 UTC, ryantheleach approved these changes

2018-08-11 12:05 UTC, merged