Register WorldGenerarorModifier with new API
SpongePowered/SpongeDocs pull request #769
Opened 2018-09-22 20:01 UTC by NeusFear

The docs have a depreciated API documented, so this solves that.

2018-09-22 21:09 UTC, ST-DDT requested changes
A few lines above this code sample there is also a textual reference to `:javadoc:GameRegistry#register(Class, T)`, that needs to be changed as well.

2018-09-22 21:09 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +    public void onWorldRegistration(GameRegistryEvent.Register<WorldGeneratorModifier> event) {
I would rather call the method `onWGenModifierRegistration` or `onWorldGeneratorModifierRegistration`.

2018-09-23 06:26 UTC, ST-DDT requested changes

2018-09-23 06:26 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +State. To register it, simply call :javadoc:`GameRegistryEvent#Register<WorldGeneratorModifier>(T)` with your modifier as the argument.
It's not a state. It's an event.
You dont call it. You listen to it and register it there.

2018-09-23 06:27 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +State. To register it, simply call :javadoc:`GameRegistryEvent#Register<WorldGeneratorModifier>(T)` with your modifier as the argument.
Also missing javadoc import.

2018-09-23 21:34 UTC, ST-DDT requested changes
The javadoc import has to be added at the top of the file (see the javadoc import block). You can try to build the docs locally or get feedback from travis CI whether you have fixed that bug.

2018-09-23 21:34 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +Event. To register it, simply lsiten to :javadoc:`GameRegistryEvent.Register` then register from there.
`lsiten` -> `listen`

2018-09-23 21:39 UTC, NeusFear reviewed
Should work now

2018-09-23 21:39 UTC, NeusFear commented on source/plugin/wgen/modifiers.rst
> +    public void onWorldRegistration(GameRegistryEvent.Register<WorldGeneratorModifier> event) {
gotcha, updated.

2018-09-23 21:39 UTC, NeusFear commented on source/plugin/wgen/modifiers.rst
> +State. To register it, simply call :javadoc:`GameRegistryEvent#Register<WorldGeneratorModifier>(T)` with your modifier as the argument.
I changed my word choice for explaining the event, and I think I fixed the Javadoc import, but I don't exactly know how they work on GitHub, so you may have to commit that change.

2018-09-23 21:56 UTC, NeusFear commented
@ST-DDT it checks out now.

2018-09-25 06:36 UTC, ST-DDT commented
Sorry, Im busy currently and cannot review it.

2018-09-27 18:32 UTC, ST-DDT requested changes
I tested the code example and the WGM was successfully registered.

2018-09-27 18:32 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +Event. To register it, simply listen to :javadoc:`GameRegistryEvent` then register from there.
I would rephrase it like this: (including some additional cross references to other pages)


````text
Now that you have created the modifier, all you have to do is register it in the :javadoc:`GameRegistry`. To do this you need to create a :doc:`listener </plugin/event/listeners>` for the :javadoc:`GameRegistryEvent.Register<WorldGeneratorModifier>` event and register your instance there, as shown in the following example:
````


With that changes you only have to change the javadoc import at the top from `GameRegistryEvent` to `GameRegistryEvent.Register`.

2018-09-27 18:32 UTC, ST-DDT commented on source/plugin/wgen/modifiers.rst
> +    org.spongepowered.api.event.game.WorldGeneratorModifier
Wrong import: Should be `org.spongepowered.api.world.gen.WorldGeneratorModifier`

2018-09-27 20:04 UTC, ST-DDT approved these changes

2018-09-27 20:06 UTC, Spongy commented
Setting up PR reference, please wait...

2018-10-20 23:08 UTC, merged