Change guideline relating to line count for PRs
SpongePowered/SpongeDocs pull request #798
Opened 2019-04-19 22:20 UTC by Hiroku

The rule against PRs that are fewer than 20 lines assumes that those PRs are for things like typos or insignificant things. In some cases, as with my only PR to Sponge, it takes 1 line to fix a crash after the author of the offending code has gone to bed. The number of lines is arbitrary, the importance of the change is not. This change better reflects the intent of the original policy.

2019-04-20 01:02 UTC, ST-DDT reviewed
What is `identifier refactoring`?

2019-04-20 01:03 UTC, Hiroku commented
> 
> 
> What is `identifier refactoring`?

I probably don't have the right terminology. I mean things like renaming all the variable names for a particular area. Can be changed, idc

2019-04-20 09:10 UTC, dualspiral commented
I'd just go simple and say `variable/method renames`.

Would it be fair to say that we should say that we don't want PR for small, _non-functional_ changes?

2019-04-20 09:15 UTC, Hiroku commented
I've modified it a bit to use simple language and dual's suggestion

2019-04-20 09:16 UTC, ST-DDT approved these changes

2019-04-20 15:47 UTC, Grauldon requested changes
SpongeDocs [Style Guide](https://docs.spongepowered.org/stable/en/contributing/spongedocs.html#style-guide) `#13` limits line to 120 characters. Please line break before the word "Instead."

2019-05-04 19:17 UTC, ST-DDT commented
@Hiroku I fixed the line length issues for you so we could merge your PR.

2019-05-04 19:17 UTC, ST-DDT approved these changes

2019-05-04 19:19 UTC, Spongy commented
Setting up PR reference, please wait...

2019-05-05 04:59 UTC, Inscrutable approved these changes

2019-05-05 05:02 UTC, phit commented
shouldn't we just link to this (https://github.com/search?q=org%3ASpongePowered+Ongoing+Minor+Issue+List&type=Issues) instead of telling people to join chat, they are most likely not getting a reply from the dev team in chats

2019-05-05 15:24 UTC, Grauldon approved these changes

2019-05-12 00:29 UTC, Inscrutable commented
> 
> 
> shouldn't we just link to this (https://github.com/search?q=org%3ASpongePowered+Ongoing+Minor+Issue+List&type=Issues) instead of telling people to join chat, they are most likely not getting a reply from the dev team in chats

It's worth doing both IMHO. We should definitely should add that link.

2019-05-12 07:16 UTC, merged