Improve config documentation
SpongePowered/SpongeDocs pull request #832
Opened 2020-04-26 13:48 UTC by ST-DDT

[**SpongeCommon**](https://github.com/SpongePowered/SpongeCommon/pull/2582) | *SpongeDocs*

Companion PR for the configuration documentation added to/improved in SpongeCommon

2020-04-26 13:49 UTC, Spongy commented
Setting up PR reference, please wait...

2020-12-04 10:28 UTC, Inscrutable requested changes
Some text here and there needs fixing. I presume some of the typos come from the original config file...
Thanks for going through this again. Maybe next time we can just `literalInclude` it ;)

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  such as a 1x1 spawn pen.Set to ``0`` to disable.
Space needed in `pen.Set`.

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  Enables focing a chunk load when an entity position is set.
focing -> forcing

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  The global collection state that should be respected by all plugins that have no specified collection state. If ``undefined`` then it is treated as disabled.
You might as well put a newline in between the sentences to be consistent.

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  It is strongly reccomended to keep this on, unless explicitly advised otherwise by a Sponge developer
reccomended -> recommended

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  Vanilla performs a lot of is area loaded checks during entity collision calculations with blocks,
We should put quotes around "is area loaded" for clarity.

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  If you want to prevent that a certain ``named`` structure is saved to the world's folder,
Change to "If you want to prevent a certain ``named`` structure being saved to the world's folder" ...
As above, so below ...

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  The configuration for each struture.
struture -> structure. x2
As above, so below ...

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +  Hides the server name in the Aikar webviewer to no leak the l33t server you are running
L337

2020-12-04 10:28 UTC, Inscrutable commented on source/server/getting-started/configuration/sponge-conf.rst
> +                        # The configuration for each struture.
struture -> structure. x2. *sigh*

2020-12-06 00:33 UTC, ST-DDT commented
Thanks for your review. I created SpongePowered/Sponge#3224 to fix these issues upstream and will update this PR with the fixed docs + includes in the next few days.

2020-12-23 14:56 UTC, Inscrutable approved these changes

2020-12-24 14:15 UTC, ST-DDT commented
It took longer than expected to update this, but I finally managed to update this.
- https://github.com/SpongePowered/SpongeDocs/pull/832/commits/b576e8ad1144b5dbad99fab84483fa6156dc9ca6 - contains the bugfixes from upstream
- in https://github.com/SpongePowered/SpongeDocs/pull/832/commits/2eef33bc478406ed600328a45fb0b0227c49a667, I moved the extensive configs/docs to separate files and embed them

2020-12-24 14:18 UTC, ST-DDT commented
Ready for merge.
Happy holidays.

2021-01-29 00:53 UTC, merged