Update for SpongeAPI 7.2
SpongePowered/SpongeDocs pull request #839
Opened 2020-05-31 11:24 UTC by ImMorpheus

2020-05-31 12:02 UTC, ST-DDT requested changes
Thanks for checking the docs.
I only found two small issues and then it should be ready for merge

2020-05-31 12:02 UTC, ST-DDT commented on source/contributing/spongedocs.rst
> +3. Program code should be contained in `inline literals <https://docutils.sourceforge.net/docs/ref/rst/roles.html#literal>`__
The https link does not work for me.
```suggestion
3. Program code should be contained in `inline literals <https://docutils.sourceforge.io/docs/ref/rst/roles.html#literal>`__
```

2020-05-31 12:02 UTC, ST-DDT commented on source/plugin/injection.rst
> +:javadoc:`SpongeExecutorService`
Missing import

2020-05-31 17:28 UTC, ST-DDT approved these changes
LGTM

2020-06-02 10:07 UTC, Inscrutable approved these changes

2020-06-02 10:08 UTC, merged